### ISSUE TITLE
5.10.1更新下吧

### ISSUE THREAD

**Issue by kennylee60** [MrHousehao/Pi-hole-Chinese#4]

**Comment by qdfansanyblog** [comment]
期待更新，感谢作者的汉化！什么时候官方能够原生支持多国语言就好了，像AdGuard home就好了。

**Comment by MrHousehao** [comment]
出了点小问题，文件死活推不上Github，我先把打包文件放在Releases里面，我晚点重装看看是不是github桌面端的问题，这Github是方便，但是我小白还是不熟悉怎样用，晚了几天，请见谅。
我也想官方原生支持啊，有些代码汉化了就出错，得要自己查、学习修改部分代码才能适应汉化。

**Comment by qdfansanyblog** [comment]
哈哈，已汉化，感谢！

**Comment by qdfansanyblog** [comment]
BUG反馈在设置界面，打勾和圆点选择项无法正常显示

**Comment by MrHousehao** [comment]
因为样式名称是保存在缓存里面的，原名是用英文名保存的，汉化完以后需要重新选择一次复选框样式，才能引用对应的复选框样式。忘记说这事了，抱歉

**Comment by MrHousehao** [comment]
我在考虑要不这个复选框样式名称就不汉化算了，因为汉化以后，会以汉化的名称将样式保存在缓存里面。官方更新之后，因为引用的样式文件会恢复英文名，而缓存中会沿用中文名称，除非用汉化文字替换掉，才能显示回来。如果在英文页面选择了英文的样式名称，汉化了之后还得再选择一次，各位看怎样比较好，我个人是喜欢把样式名称汉化了的。毕竟涉及这个样式的就三个文件『1、admin/目录下的settings.php，2、admin/style/vendor/目录下的icheck-bootstrap.min.css和icheck-material.min.css』其中1的文件官方会有修改，2的两个文件见官方好几个版本都没修改过。所以理论上来说用上一版本的文件替换也是可以的，然后新汉化出了，再把1的文件换成新的，是不会影响的。

**Comment by MrHousehao** [comment]
> 因为样式名称是保存在缓存里面的，原名是用英文名保存的，汉化完以后需要重新选择一次复选框样式，才能引用对应的复选框样式。忘记说这事了，抱歉
